version: '3.1'
services:
  pokemon-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "3010:3010"
    depends_on:
     - redis
    links:
     - redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
